name: Manual Approval & Continue

on:
  workflow_dispatch:
    inputs:
      approval:
        description: "Do you approve execution? (yes/no)"
        required: true
        type: choice
        options:
          - "yes"
          - "no"

permissions:
  contents: read

jobs:
  continue-pipeline:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval == 'yes' }}
    steps:
      - name: Continue with Failover Execution
        run: echo "Approval received. Proceeding with failover steps..."

  cancel:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval == 'no' }}
    steps:
      - name: Cancel Execution
        run: echo "Pipeline stopped as per user request."
