name: Failover Pipeline
 
on:
  push:
    branches:
      - main


jobs:
  Hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: script
        run: echo 'Hello, world! - $WORKSPACE_ID '
        

  wait-for-approval:
    runs-on: ubuntu-latest
    needs: Hello-world
    environment: manual-approval  # ⬅️ Requires manual approval in GitHub Environments
    steps:
      - name: Proceed After Approval
        run: echo "Approval granted! Executing next steps."
 
  handle-rejection:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: cancelled() || failure()  # ⬅️ This step runs if approval was denied
    steps:
      - name: Fail the Workflow
        run: |
          echo "Approval was denied. Failing the workflow!"
    
  Thank-you:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: success()
    steps:
      - name: script
        run: echo 'Thank You!'
