name: Failover Pipeline

on:
  workflow_dispatch: # This allows manual triggering

permissions:
  contents: write

jobs:
  wait-for-approval:
    needs: send-teams-alert
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for manual approval
        run: echo "Please approve the pipeline manually via GitHub Actions UI."
    
    outputs:
      approval_required: "true"

  manual-approval:
    needs: wait-for-approval
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval == 'yes' }}
    steps:
      - name: Proceed with Failover Pipeline
        run: echo "Approval received. Proceeding to the next stage."

  cancel:
    needs: wait-for-approval
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval == 'no' }}
    steps:
      - name: Cancel Pipeline
        run: echo "Pipeline execution stopped due to disapproval."
