name: Failover Pipeline

on:
  push:
    branches:
      - main
 
permissions:
  contents: read

jobs:
  send-teams-alert:
    runs-on: ubuntu-latest
    steps:
      - name: script
        run: echo 'Hello, world!'
        

  wait-for-approval:
    runs-on: ubuntu-latest
    needs: send-teams-alert
    environment: manual-approval  # ⬅️ Requires manual approval in this environment
    steps:
      - name: Proceed After Approval
        run: echo "Approval granted! Executing next steps."

  execute-failover:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    steps:
      - name: Perform Failover Actions
        run: echo "Executing failover actions..."
